name: Test Azure Login

on:
  workflow_dispatch:

jobs:
  login-test:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login with OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true

    - name: Show current Azure account
      run: az account show

    - name: Build and push React image
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/react-ui ./frontend
        az acr login --name ${{ secrets.ACR_NAME }}
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/react-ui

    - name: Build and push React image
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/react-ui ./frontend
        az acr login --name ${{ secrets.ACR_NAME }}
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/react-ui

    - name: (Optional) Deploy to Azure Container Apps
      run: |
        az containerapp update \
          --name react-ui \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --image ${{ secrets.ACR_NAME }}.azurecr.io/react-ui


